name = "TDD"
uuid = "2807c68b-f71b-41d3-873c-2a2ccc98fb26"
authors = ["Brendan Dang <b.dang@wustl.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
